### ISSUE TITLE
Errno 11001: getaddrinfo failed

### ISSUE THREAD

**Issue by aiyoof** [davesc63/GeoPort#10] opened 2024-03-31 05:03 UTC
Hi, I had to reset my phone and could not turn developer mode back on, so I had Geoport turn it on and that worked. Now when I try to set my location though it says it's done it successfully but produces this error on the application and hasn't changed location. Is there anything on my end that is going wrong? Doing this through windows on a iOS 17.4.1 iPhone 14. 
![Screenshot 2024-03-31 000148](https://github.com/davesc63/GeoPort/assets/146498806/a4e8aa6c-cb79-4298-a8e4-9467b5cb2536)

**Comment by davesc63** [comment] 2024-03-31 05:55
Great to hear GeoPort could set your developer mode. I’ve had to use it when I upgrade to iPhone 15!

This error is a new one for me. Can you please show the output from before this. I am keen to see  the entries related to “wintun”

to get this far in the app it would have installed the driver and it believes it’s created a secure tunnel to the device. But if we get an ip address info there’s got to be something not quite right. 

Im just wondering if the tunnel actually isn’t created but an error returned back values that the app is using to try to create a tunnel. We should have an ipv6 address and a 5 digit port number

**Comment by jmswangit** [comment] 2024-03-31 20:59
```
2024-03-31 15:26:27 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:26:27] "POST /connect_device HTTP/1.1" 200 -
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Installing driver 15.14
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Extracting driver
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Installing driver
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Creating adapter
address:  fd56:582:92b0::1
port:  52520
Traceback (most recent call last):
  File "pymobiledevice3\utils.py", line 54, in wrapper
  File "pymobiledevice3\remote\core_device_tunnel_service.py", line 225, in keep_alive_task
  File "qh3\asyncio\protocol.py", line 93, in ping
ConnectionError
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Removed orphaned adapter "wintun 1"
Stop Existing Location Thread
Error setting location: [Errno 11001] getaddrinfo failed
```

**Comment by davesc63** [comment] 2024-03-31 21:14
@jmswangit Can you please prevoide more of the log prior to this?
Also, how many "devices" are being discovered?

**Comment by jmswangit** [comment] 2024-03-31 21:25
```
base dir =  C:\Users\jmswa\AppData\Local\Temp\_MEI248282
Current platform: Windows
App Version =  1.0.2
2024-03-31 15:24:46 Swan-PC pyi_splash[9428] INFO A connection to the splash screen was successfully established.
clear splash
2024-03-31 15:24:46 Swan-PC pyuac[9428] INFO isUserAdmin - CheckTokenMembership returned: True
 * Serving Flask app 'main'
 * Debug mode: on
2024-03-31 15:24:48 Swan-PC werkzeug[9428] INFO WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:54321
2024-03-31 15:24:48 Swan-PC werkzeug[9428] INFO Press CTRL+C to quit
GitHub Version =  1.0.2
2024-03-31 15:24:49 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:24:49] "GET / HTTP/1.1" 200 -
2024-03-31 15:24:49 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:24:49] "GET /api/fuel_types?region=All HTTP/1.1" 200 -
Secured Device List is:  [MuxDevice(devid=51, serial='00008120-0012106A2E50A01E', connection_type='USB'), MuxDevice(devid=50, serial='00008120-0012106A2E50A01E', connection_type='Network')]
2024-03-31 15:24:49 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:24:49] "GET /api/data/?region=All HTTP/1.1" 404 -
[{'Identifier': '00008120-0012106A2E50A01E', 'DeviceClass': 'iPhone', 'DeviceName': 'iPhone', 'BuildVersion': '21D61', 'ProductVersion': '17.3.1', 'ProductType': 'iPhone15,5', 'ConnectionType': 'USB'}, {'Identifier': '00008120-0012106A2E50A01E', 'DeviceClass': 'iPhone', 'DeviceName': 'iPhone', 'BuildVersion': '21D61', 'ProductVersion': '17.3.1', 'ProductType': 'iPhone15,5', 'ConnectionType': 'USB'}]
2024-03-31 15:24:49 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:24:49] "GET /list_devices HTTP/1.1" 200 -
2024-03-31 15:24:49 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:24:49] "POST /update_location HTTP/1.1" 200 -
data:  {'udid': '00008120-0012106A2E50A01E', 'ios_version': '17.3.1'}
udid:  00008120-0012106A2E50A01E
Dev Check result:  True
Developer Mode is true
Passed Developer Mode check
iOS 17+ detected
2024-03-31 15:24:51 Swan-PC wintun[9428] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-03-31 15:24:51 Swan-PC wintun[9428] INFO WeTestUsbNcm driver use current version: 11.36.59.886, [11.36.59.886] tested.
2024-03-31 15:24:51 Swan-PC wintun[9428] INFO use existing WeTestUsbFilter driver.
2024-03-31 15:24:51 Swan-PC wintun[9428] INFO use existing WeTestUsbNcm driver.
Devices: [<RemoteServiceDiscoveryService PRODUCT:iPhone15,5 VERSION:17.3.1 UDID:00008120-0012106A2E50A01E>]
Start QUIC tunnel
2024-03-31 15:24:53 Swan-PC wintun[9428] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-03-31 15:24:53 Swan-PC wintun[9428] INFO WeTestUsbNcm driver use current version: 11.36.59.886, [11.36.59.886] tested.
2024-03-31 15:24:53 Swan-PC wintun[9428] INFO use existing WeTestUsbFilter driver.
2024-03-31 15:24:53 Swan-PC wintun[9428] INFO use existing WeTestUsbNcm driver.
2024-03-31 15:24:53 Swan-PC wintun[9428] INFO Failed to find matching adapter name: Element not found. (Code 0x00000490)
2024-03-31 15:24:53 Swan-PC wintun[9428] INFO Waiting for existing driver to unload from kernel
RSD Data:  (None, None)
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Failed to unload existing driver, which means a reboot will likely be required
Connect Device function completed
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Removing existing driver 0.14
2024-03-31 15:26:27 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:26:27] "POST /connect_device HTTP/1.1" 200 -
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Installing driver 15.14
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Extracting driver
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Installing driver
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Creating adapter
address:  fd56:582:92b0::1
port:  52520
Traceback (most recent call last):
  File "pymobiledevice3\utils.py", line 54, in wrapper
  File "pymobiledevice3\remote\core_device_tunnel_service.py", line 225, in keep_alive_task
  File "qh3\asyncio\protocol.py", line 93, in ping
ConnectionError
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Removed orphaned adapter "wintun 1"
Stop Existing Location Thread
Error setting location: [Errno 11001] getaddrinfo failed
2024-03-31 15:26:59 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:26:59] "POST /set_location HTTP/1.1" 200 -
2024-03-31 15:32:03 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:32:03] "POST /update_location HTTP/1.1" 200 -
2024-03-31 15:32:03 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:32:03] "POST /update_location HTTP/1.1" 200 -
Stop Existing Location Thread
2024-03-31 15:32:05 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:32:05] "POST /set_location HTTP/1.1" 200 -
Error setting location: [Errno 11001] getaddrinfo failed
Stop Existing Location Thread
Error setting location: [Errno 11001] getaddrinfo failed
2024-03-31 15:32:08 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:32:08] "POST /set_location HTTP/1.1" 200 -
Stop Existing Location Thread
Error setting location: [Errno 11001] getaddrinfo failed
2024-03-31 15:32:10 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:32:10] "POST /set_location HTTP/1.1" 200 -
Stop Existing Location Thread
Error setting location: [Errno 11001] getaddrinfo failed
2024-03-31 15:32:12 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:32:12] "POST /set_location HTTP/1.1" 200 -
Stop Existing Location Thread
2024-03-31 15:32:12 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:32:12] "POST /set_location HTTP/1.1" 200 -
Error setting location: [Errno 11001] getaddrinfo failed
Stop Existing Location Thread
Error setting location: [Errno 11001] getaddrinfo failed
2024-03-31 15:40:05 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:40:05] "POST /set_location HTTP/1.1" 200 -
Stop Existing Location Thread
2024-03-31 15:40:07 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:40:07] "POST /set_location HTTP/1.1" 200 -
Error setting location: [Errno 11001] getaddrinfo failed
Stop Existing Location Thread
2024-03-31 15:40:07 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:40:07] "POST /set_location HTTP/1.1" 200 -
Error setting location: [Errno 11001] getaddrinfo failed

```

I have seen 2 sometimes in the GUI, but I don't know if that was the case this time.

**Comment by davesc63** [comment] 2024-03-31 21:52
@jmswangit Awesome! Thank you for the details. This helps :)

I see a few issues here - thankfully part is already addressed in version 2.0 (coming in a few days)

issue 1: my bad code. I’m not filtering the “network” option so you see two devices in the list. Both say “USB” but one is actually a network / WiFi option

issue 2: this is why I believe we aren’t connecting: `RSD Data:  (None, None)`  but a little later we actually have those details as seen here:
`address:  fd56:582:92b0::1
port:  52520`

might be a race condition

does this happen all the time, or sometimes?

**Comment by jmswangit** [comment] 2024-03-31 21:55
Unfortunately today is the only time i have attempted to use the app.

**Comment by aiyoof** [comment] 2024-04-01 00:11
Apologies for my delayed response, but thank you @jmswangit for filling in! As for me, this happened for me yesterday and today when I tried it for the second time.

**Comment by davesc63** [comment] 2024-04-01 00:51
@aiyoof - can I confirm that it’s never worked for you, or it’s happened twice? Just trying to clarify the statements. Which then helps me to understand if it’s a race condition. Because on my windows machines it works every time

**Comment by jmswangit** [comment] 2024-04-01 01:06
No OP again, but just wanted to add context that I’m an iPhone 15 Plus user, on 17.3.1, trying to spoof on PC. I’m sure all of that is probably reflected in my error code, but I wanted to share either way.

**Comment by aiyoof** [comment] 2024-04-01 01:13
> @aiyoof - can I confirm that it’s never worked for you, or it’s happened twice? Just trying to clarify the statements. Which then helps me to understand if it’s a race condition. Because on my windows machines it works every time

It has worked for me, on the first version, before my iPhone was at the latest update, but yesterday and today it hasn't worked.

**Comment by davesc63** [comment] 2024-04-01 09:57
@jmswangit & @aiyoof - looking over the code I have a 3 second delay waiting for the tunnel to be established.

If you can / want, please try connecting a few more times to see if it succeeds. It should, but I might need to add some code to do a little more waiting / checking

**Comment by aiyoof** [comment] 2024-04-01 22:24
I tried a couple of times throughout the day and there still is no luck, perhaps one problem that may be a part of it is that my Norton Antivirus is saying that it's blocking some suspicious actions by GeoPort. Is anyone else having a similar problem and if so does anyone know how to block it I can't find anything on the Norton application that can. I don't know if that's a contributor to the problem or what.

**Comment by davesc63** [comment] 2024-04-01 22:29
I think this would be an issue, it may not like installing the driver. Although Norton should block the entire app if it thinks there's a problem! Norton would more be allowing GeoPort to function, if it has picked up an action it doesn't like - it should be in the log.

My own endpoint security software doesn't like that the app would make external API calls to an IP Geolocation service. So I have changed a section of code to now use a python module called pycountry for the upcoming release

**Comment by aiyoof** [comment] 2024-04-01 22:34
That makes sense, again I don't know if that is the root cause of all this as it originally all worked before I reset my phone, but thank you again for your help and prompt communication!

**Comment by davesc63** [comment] 2024-04-01 22:37
Reading the log from @jmswangit - their situation suits this sort of scenario. However looking closer again We can see here:
RSD Data:  (None, None)
**2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Failed to unload existing driver, which means a reboot will likely be required
Connect Device function completed**
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Removing existing driver 0.14
2024-03-31 15:26:27 Swan-PC werkzeug[9428] INFO 127.0.0.1 - - [31/Mar/2024 15:26:27] "POST /connect_device HTTP/1.1" 200 -
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Installing driver 15.14
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Extracting driver
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Installing driver
2024-03-31 15:26:27 Swan-PC wintun[9428] INFO Creating adapter
address:  fd56:582:92b0::1
port:  52520
Traceback (most recent call last):
  File "pymobiledevice3\utils.py", line 54, in wrapper
  File "pymobiledevice3\remote\core_device_tunnel_service.py", line 225, in keep_alive_task
  File "qh3\asyncio\protocol.py", line 93, in ping
ConnectionError

Your machine may need a reboot.
The final connection error is somewhat self explanatory - The code can't communicate with the device as intended. So the windows driver install hasn't completed properly and therefore our tunnel can't be established.

If I was to look at this with @aiyoof lens, perhaps Norton doesn't like this step and has blocked the vpn tunnel setup / adapter creation

On Windows - You can check control panel - network connections and see if a network adapter named "wintun" is being created. Keep the window open while trying to "Connect Device"... You may see the adapter appear then get removed perhaps which could indicate something like Norton is tearing it down (wild theory)

**Comment by aiyoof** [comment] 2024-04-02 01:52
After restarting my laptop, it was finally able to work, crazy how that just fixes everything. And yes, after looking in the control panel, "wintun" was created and wasn't torn down by Norton after this time. Thank you so much again for your communication and hard work and I'm looking forward to the next update!

**Closed** 2024-04-02 03:17 UTC
